[package]
name = "smoo_webusb"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3.70"
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "0.3.70", features = [
    "Navigator",
    "Usb",
    "UsbDevice",
    "UsbDeviceFilter",
    "UsbDeviceRequestOptions",
    "Window"
] }
